### ISSUE TITLE
streaming tag-only changes

### ISSUE THREAD

**Issue by kriscarle** [developmentseed/planet-stream#16]
Hi guys,

As far as I can tell, changes with just tags don't make it through. For our loggingroads.org project we have users that just add start_date tags to roads and we want to include those users in the leaderboards. We can still count the number of changes from the metadata even though it won't adding anything to the road km totals.

I'm looking at the code now trying to figure out the best way to implement this. Any ideas? 

I've confirmed that the metadata is written to redis, but I guess the augmented diff doesn't include them so it never gets joined up and sent through. 

Thanks!

**Comment by kriscarle** [comment]
I was originally assuming that the augmented diff didn't include tag changes, but I've confirmed that it is the AugmentedDiffParser code that is dropping the data. It appears to be dropping changesets with only one element, including changesets that were split if they exceed the opts.limit and ended up with only one element. I'll submit a PR.

This is confirmed by the larger number of "No tracked changes in changeset" messages that I see in the osm-stats-workers logs, including duplicates for the same changeset id 

![image](https://cloud.githubusercontent.com/assets/2431570/15980016/dfaab9ec-2f35-11e6-8806-5413e1e1189b.png)

**Comment by kamicut** [comment]
This was merged in in #19, thanks for the report and PR!
