### ISSUE TITLE
Local version of planet-stream .onValue never fired?

### ISSUE THREAD

**Issue by rustyb** [developmentseed/planet-stream#21]
Hi Guys - Have been trying to set up planet-stream for the last few days. 

Unfortunately planetstream.onValue() never seems to be called. As in you never see the changeset printed in the console as I watch the docker logs.

``` js
// Filter out records that have no metadata
planetstream.map(JSON.parse)
.filter(function (data) {
    return data.hasOwnProperty('metadata');

})
// print out record
.onValue(function (obj) {
  var payload = JSON.stringify(obj);
  console.log(payload);
}); 
```

Looking at the output it would seem onValue should be called after the changeset is returned. However this is not the case for some reason. 

Not in the below that I have modified `lib/planetstream.js` to try print out the `metadata.id` being queried in redis.

<img width="762" alt="screen shot 2016-08-18 at 16 13 50" src="https://cloud.githubusercontent.com/assets/53086/17776927/d368b44a-655e-11e6-841e-b30a74323219.png">

Any idea how I might be able to fix this?

**Comment by kamicut** [comment]
@rustyb sorry I missed this. Could this be a delay in Overpass? It can take some time to respond (sometimes up to 10 minutes)

**Comment by rustyb** [comment]
Hi @kamicut thanks for getting back to me. I don't think so as i left if for like 10 hours and it never fired, so I'm assuming it's getting stuck somewhere along the way.

When I rolled back to v 0.4.0 it works away fine, has been powering our slackbot for a few weeks now.

**Comment by kamicut** [comment]
@rustyb Just saw your [blog post](http://cbroderick.me/blog/2016/08/20/osm-changeset-slack-notifications/). Thanks for trying it out! 

Do you mean roll back from 0.4 to 0.3.2? Could you share your node version, that could help in debugging.

**Comment by rustyb** [comment]
@kamicut using node v6.0 in the docker image.

DOH! bit of a brain fart there, yes back to 0.3.2 before the to Kue for the queuing.

**Comment by kamicut** [comment]
Great, thanks. I'll look into it.

**Comment by rustyb** [comment]
Howdy @kamicut I've been trying to get this work again, still to no avail.

I've discovered at least now it seems to be returning part of a promise to the stream:

```json
{
  "isFulfilled": false,
  "isRejected": false
}
```

Any idea how I might be able to fix that so things actually get posted to the stream?

**Comment by kamicut** [comment]
Hey @rustyb I'm planning on rewriting `planet-stream` using @mojodna's [osm-replication-streams](https://github.com/mojodna/osm-replication-streams). Maybe that library could help with what you need? It still doesn't have the augmented diff stream, but if the changeset and changes streams are enough it could be useful.
